// Builds the image-generation prompt for an episode's poster/cover art.
//
// Design notes:
// - Explicit camera/composition/lighting direction, not just subject
//   description - this is what actually separates "generic fantasy blob"
//   output from something that reads as a real poster.
// - Each creature's primaryType.color (already generated in creatures.js) is
//   passed through as a literal hex code for rim-lighting, so the poster's
//   color language is directly tied to the type system instead of guessing
//   at color from words like "Fire" or "Water".
// - The arena is part of the scene - generated by arenas.js for the
//   script/commentary and reused here so the artwork matches the episode's
//   actual setting instead of a generic sky.
// - No negative_prompt support on this model, so exclusions (no text, no
//   watermark, no split-screen) are phrased as positive instructions instead.
// - Aug 9, 2026: art direction changed from painterly/photoreal fantasy to a
//   bold flat-vector illustration style, closer to tech-editorial podcast
//   cover art, per explicit reference. Title text is deliberately still
//   excluded from the generated image (diffusion models render legible text
//   unreliably) - the title stays as separate HTML on the page, same as
//   today, so any bolder title treatment should be a frontend/CSS change,
//   not a prompt change.
//
// Fixed Aug 2026: this file was still building each creature's visual
// description from `creature.visualDescription` - a field that only
// existed on the old fictional-creature schema. The Aug 7 creatures.js
// rebuild (real Pokemon via @pkmn/dex) never had that field, so every
// poster since has been prompted with a literal "undefined" for what each
// creature actually looks like - the model had type-color and arena
// context but zero idea which creature it was drawing. Replaced with the
// real schema's name/category/type fields, which is exactly what
// script.js's own commentary is already built from (see script.js's use
// of primaryType/secondaryType/category), so the poster and the narration
// are now describing the same creature from the same data.

// Loud failure instead of a silent "undefined" poster if creatures.js's
// schema drifts again - this exact class of bug (a field poster.js/
// script.js/index.js depends on quietly disappearing from creatures.js)
// has already happened twice in this project.
function assertCreatureShape(creature, label) {
  if (!creature || !creature.name || !creature.primaryType || !creature.primaryType.color || !creature.primaryType.name) {
    throw new Error(
      `poster.js: ${label} is missing expected fields (name / primaryType.name / primaryType.color) - ` +
      `creatures.js's schema may have changed again. Got keys: ${creature ? Object.keys(creature).join(', ') : 'null'}`
    );
  }
}

function sizeCue(heightFt) {
  if (heightFt == null) return '';
  if (heightFt >= 15) return 'towering, massive scale, ';
  if (heightFt >= 6) return 'large and imposing, ';
  if (heightFt <= 1.5) return 'small and compact, ';
  return '';
}

function creatureVisualLine(creature) {
  const typeLabel = creature.secondaryType
    ? `${creature.primaryType.name}/${creature.secondaryType.name}-type`
    : `${creature.primaryType.name}-type`;
  const article = /^[aeiou]/i.test(creature.primaryType.name) ? 'an' : 'a';
  const categoryLabel = creature.category ? ` (the ${creature.category})` : '';
  return (
    `the real Pokemon ${creature.name}${categoryLabel}, ${article} ${typeLabel} creature, ` +
    `${sizeCue(creature.height)}rendered accurately and recognizably as its actual species design`
  );
}

function buildPosterPrompt(creatureA, creatureB, arena) {
  assertCreatureShape(creatureA, 'creatureA');
  assertCreatureShape(creatureB, 'creatureB');

  const arenaLine = arena
    ? `The battle takes place at ${arena.description}, with ${arena.weather} in the air.`
    : 'The battle takes place in a dramatic, elemental landscape.';

  return (
    `Epic fantasy creature-battle poster art, single unified cinematic scene, ` +
    `low-angle dynamic action shot, rule-of-thirds composition, both creatures ` +
    `mid-clash charging toward each other from opposite sides. ` +
    `${arenaLine} ` +
    `On the left: ${creatureVisualLine(creatureA)}. Rim-lit with a glowing aura of ` +
    `color ${creatureA.primaryType.color}, matching its ${creatureA.primaryType.name} energy. ` +
    `On the right, facing off against them: ${creatureVisualLine(creatureB)}. Rim-lit with a glowing ` +
    `aura of color ${creatureB.primaryType.color}, matching its ${creatureB.primaryType.name} energy. ` +
    `Bold modern flat-vector illustration style, like a tech-editorial or news-explainer ` +
    `podcast cover, not photorealistic painting. Thick clean outlines, vibrant saturated ` +
    `color blocking, high-contrast graphic silhouettes, minimal fine surface detail, ` +
    `strong poster-thumbnail readability even at small size, dynamic diagonal composition, ` +
    `sense of motion and impact between the two subjects. Keep the upper third of the frame ` +
    `relatively open and uncluttered. ` +
    `No text, no logos, no watermarks, no borders, no split-screen.`
  ).slice(0, 2000);
}

// A stable per-episode seed keeps regenerating the same matchup
// (e.g. a manual retry) visually consistent rather than fully random each
// time, while still varying naturally across different creature/arena combos.
function seedFromNames(creatureA, creatureB, arenaName) {
  const str = `${creatureA.name}|${creatureB.name}|${arenaName || ''}`;
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  }
  return hash % 2147483647;
}

async function generatePosterOnce(creatureA, creatureB, arena, env) {
  const prompt = buildPosterPrompt(creatureA, creatureB, arena);
  const response = await env.AI.run('@cf/leonardo/lucid-origin', {
    prompt,
    width: 1216,
    height: 1216,
    guidance: 7,
    num_steps: 30,
    seed: seedFromNames(creatureA, creatureB, arena?.name)
  });
  const binaryString = atob(response.image);
  const bytes = Uint8Array.from(binaryString, (c) => c.codePointAt(0));
  return bytes;
}

async function generatePoster(creatureA, creatureB, arena, env) {
  try {
    return await generatePosterOnce(creatureA, creatureB, arena, env);
  } catch (firstErr) {
    console.error('Poster generation failed once, retrying:', firstErr.message);
    try {
      return await generatePosterOnce(creatureA, creatureB, arena, env);
    } catch (secondErr) {
      throw new Error(`Poster generation failed twice, giving up: ${secondErr.message}`);
    }
  }
}

export { buildPosterPrompt, generatePoster };
