// Builds the image-generation prompt for an episode's poster/cover art.
//
// Design notes:
// - Explicit camera/composition/lighting direction, not just subject
//   description - this is what actually separates "generic fantasy blob"
//   output from something that reads as a real poster.
// - Each creature's primaryType.color (already generated in creatures.js) is
//   passed through as a literal hex code for rim-lighting, so the poster's
//   color language is directly tied to the type system instead of guessing
//   at color from words like "Fire" or "Water".
// - The arena is part of the scene - generated by arenas.js for the
//   script/commentary and reused here so the artwork matches the episode's
//   actual setting instead of a generic sky.
// - No negative_prompt support on this model, so exclusions (no text, no
//   watermark, no split-screen) are phrased as positive instructions instead.
// - Aug 9, 2026: art direction changed from painterly/photoreal fantasy to a
//   bold flat-vector illustration style, closer to tech-editorial podcast
//   cover art, per explicit reference. Title text is deliberately still
//   excluded from the generated image (diffusion models render legible text
//   unreliably) - the title stays as separate HTML on the page, same as
//   today, so any bolder title treatment should be a frontend/CSS change,
//   not a prompt change.
//
// - Aug 22, 2026: art direction changed again, from flat-vector
//   tech-editorial to Japanese anime style, per explicit reference.
//   First pass leaned into a Gundam mecha reframing (creatures rendered as
//   armored mobile suits) - feedback was that this went too far from the
//   show's actual subject matter (real creatures, Pokemon-adjacent) and
//   away from "anime" as a rendering style. Reverted the mecha framing;
//   creatures.js's organic, type-based visualDescription is now used
//   directly again, just rendered in a Japanese anime illustration style
//   (cel-shading, bold linework, vibrant color) rather than as mechs.
//
// Fixed Aug 2026: this file was still building each creature's visual
// description from `creature.visualDescription` - a field that only
// existed on the old fictional-creature schema. The Aug 7 creatures.js
// rebuild (real Pokemon via @pkmn/dex) never had that field, so every
// poster since has been prompted with a literal "undefined" for what each
// creature actually looks like. At the time, this was fixed by switching
// to the real schema's name/category/type fields directly.
//
// CHANGED 2026-08-22: creatures.js has since re-added a real
// `visualDescription` field (see creatures.js's own header note: "for
// poster.js's image-generation prompt - generic, type-based, no species
// name/likeness"), built from a proper per-type texture/color/build table
// (TYPE_VISUAL_STYLE). This file no longer re-derives its own thinner
// description from primaryType/category - it reads creatures.js's field
// directly, which is both richer and keeps the two files from
// independently drifting on what "trademark-safe" means. This also
// reverses a regression: the name/category-based version introduced here
// had drifted into asking the model to render "the real Pokemon {name}...
// recognizably as its actual species design" - the exact copyrighted-
// likeness problem this field exists to avoid.

// Loud failure instead of a silent "undefined" poster if creatures.js's
// schema drifts again - this exact class of bug (a field poster.js/
// script.js/index.js depends on quietly disappearing from creatures.js)
// has already happened twice in this project.
function assertCreatureShape(creature, label) {
  if (!creature || !creature.name || !creature.primaryType || !creature.primaryType.color || !creature.primaryType.name || !creature.visualDescription) {
    throw new Error(
      `poster.js: ${label} is missing expected fields (name / primaryType.name / primaryType.color / visualDescription) - ` +
      `creatures.js's schema may have changed again. Got keys: ${creature ? Object.keys(creature).join(', ') : 'null'}`
    );
  }
}

function sizeCue(heightFt) {
  if (heightFt == null) return '';
  if (heightFt >= 15) return 'towering, massive scale, ';
  if (heightFt >= 6) return 'large and imposing, ';
  if (heightFt <= 1.5) return 'small and compact, ';
  return '';
}

// creatures.js already builds a trademark-safe, per-type visual
// description specifically for this prompt (colors, texture, build - see
// its TYPE_VISUAL_STYLE table) - use it directly rather than maintaining a
// second, independent "make up a visual" code path here. Two files each
// guessing at how to describe a creature safely is exactly how this
// project ended up with a species-recognizable prompt in the first place.
function creatureVisualLine(creature) {
  const desc = creature.visualDescription.replace(/\.\s*$/, '');
  return `${sizeCue(creature.height)}${desc}`;
}

function buildPosterPrompt(creatureA, creatureB, arena) {
  assertCreatureShape(creatureA, 'creatureA');
  assertCreatureShape(creatureB, 'creatureB');

  const arenaLine = arena
    ? `The battle takes place at ${arena.description}, with ${arena.weather} in the air.`
    : 'The battle takes place in a dramatic, elemental landscape.';

  return (
    `Epic anime creature-battle poster art, single unified cinematic scene, ` +
    `low-angle dynamic action shot, rule-of-thirds composition, both creatures ` +
    `mid-clash charging toward each other from opposite sides. ` +
    `${arenaLine} ` +
    `On the left: ${creatureVisualLine(creatureA)}. Rim-lit with a glowing aura of ` +
    `color ${creatureA.primaryType.color}, matching its ${creatureA.primaryType.name} energy. ` +
    `On the right, facing off against them: ${creatureVisualLine(creatureB)}. Rim-lit with a glowing ` +
    `aura of color ${creatureB.primaryType.color}, matching its ${creatureB.primaryType.name} energy. ` +
    `Japanese anime illustration style, in the spirit of a monster-collecting ` +
    `trading-card-game key visual - vibrant saturated color, cel-shaded ` +
    `rendering, bold clean linework, expressive dynamic poses, glossy ` +
    `highlight accents, painterly anime backgrounds with dramatic sky and ` +
    `light rays, not photorealistic and not a mechanical/armored design - ` +
    `creatures should read as living, organic beings. High-contrast anime ` +
    `lighting, strong poster-thumbnail readability even at small size, ` +
    `dynamic diagonal composition, sense of motion and impact between the ` +
    `two subjects. Keep the upper third of the frame relatively open and ` +
    `uncluttered. ` +
    `No text, no logos, no watermarks, no borders, no split-screen.`
  ).slice(0, 2000);
}

// A stable per-episode seed keeps regenerating the same matchup
// (e.g. a manual retry) visually consistent rather than fully random each
// time, while still varying naturally across different creature/arena combos.
function seedFromNames(creatureA, creatureB, arenaName) {
  const str = `${creatureA.name}|${creatureB.name}|${arenaName || ''}`;
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  }
  return hash % 2147483647;
}

async function generatePosterOnce(creatureA, creatureB, arena, env) {
  const prompt = buildPosterPrompt(creatureA, creatureB, arena);
  const response = await env.AI.run('@cf/leonardo/lucid-origin', {
    prompt,
    width: 1216,
    height: 1216,
    guidance: 7,
    num_steps: 30,
    seed: seedFromNames(creatureA, creatureB, arena?.name)
  });
  const binaryString = atob(response.image);
  const bytes = Uint8Array.from(binaryString, (c) => c.codePointAt(0));
  return bytes;
}

async function generatePoster(creatureA, creatureB, arena, env) {
  try {
    return await generatePosterOnce(creatureA, creatureB, arena, env);
  } catch (firstErr) {
    console.error('Poster generation failed once, retrying:', firstErr.message);
    try {
      return await generatePosterOnce(creatureA, creatureB, arena, env);
    } catch (secondErr) {
      throw new Error(`Poster generation failed twice, giving up: ${secondErr.message}`);
    }
  }
}

export { buildPosterPrompt, generatePoster };
