// Builds the image-generation prompt for an episode's poster/cover art.
//
// Design notes:
// - Explicit camera/composition/lighting direction, not just subject
//   description - this is what actually separates "generic fantasy blob"
//   output from something that reads as a real poster.
// - Each creature's primaryType.color (already generated in creatures.js) is
//   passed through as a literal hex code for rim-lighting, so the poster's
//   color language is directly tied to the type system instead of guessing
//   at color from words like "Fire" or "Water".
// - The arena is now part of the scene - previously generated by
//   arenas.js for the script/commentary and silently thrown away when it
//   came to the poster background. Reusing it here means the artwork
//   actually matches the episode's setting instead of a generic sky.
// - No negative_prompt support on this model, so exclusions (no text, no
//   watermark, no split-screen) are phrased as positive instructions instead.
function buildPosterPrompt(creatureA, creatureB, arena) {
  const arenaLine = arena
    ? `The battle takes place at ${arena.description}, with ${arena.weather} in the air.`
    : 'The battle takes place in a dramatic, elemental landscape.';

  return (
    `Epic fantasy creature-battle poster art, single unified cinematic scene, ` +
    `low-angle dynamic action shot, rule-of-thirds composition, both creatures ` +
    `mid-clash charging toward each other from opposite sides. ` +
    `${arenaLine} ` +
    `On the left: ${creatureA.visualDescription} Rim-lit with a glowing aura of ` +
    `color ${creatureA.primaryType.color}, matching its ${creatureA.primaryType.name} energy. ` +
    `On the right, facing off against them: ${creatureB.visualDescription} Rim-lit with a glowing ` +
    `aura of color ${creatureB.primaryType.color}, matching its ${creatureB.primaryType.name} energy. ` +
    `Rich painterly digital-art style, dramatic chiaroscuro lighting, crisp detailed ` +
    `silhouettes against the background, high dynamic range color grading, ` +
    `sense of motion and impact between the two subjects. ` +
    `Movie-poster framing, no text, no logos, no watermarks, no borders, no split-screen.`
  ).slice(0, 2000);
}

// A stable per-episode seed keeps regenerating the same matchup
// (e.g. a manual retry) visually consistent rather than fully random each
// time, while still varying naturally across different creature/arena combos.
function seedFromNames(creatureA, creatureB, arenaName) {
  const str = `${creatureA.name}|${creatureB.name}|${arenaName || ''}`;
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31 + str.charCodeAt(i)) >>> 0;
  }
  return hash % 2147483647;
}

async function generatePosterOnce(creatureA, creatureB, arena, env) {
  const prompt = buildPosterPrompt(creatureA, creatureB, arena);
  const response = await env.AI.run('@cf/leonardo/lucid-origin', {
    prompt,
    width: 1216,
    height: 1216,
    guidance: 7,
    num_steps: 30,
    seed: seedFromNames(creatureA, creatureB, arena?.name)
  });
  const binaryString = atob(response.image);
  const bytes = Uint8Array.from(binaryString, (c) => c.codePointAt(0));
  return bytes;
}

async function generatePoster(creatureA, creatureB, arena, env) {
  try {
    return await generatePosterOnce(creatureA, creatureB, arena, env);
  } catch (firstErr) {
    console.error('Poster generation failed once, retrying:', firstErr.message);
    try {
      return await generatePosterOnce(creatureA, creatureB, arena, env);
    } catch (secondErr) {
      throw new Error(`Poster generation failed twice, giving up: ${secondErr.message}`);
    }
  }
}

export { buildPosterPrompt, generatePoster };
